version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/gcc:latest  # or another image with cmake and make installed
    steps:
      - checkout  # Checkout the source code

      - run:
          name: Create Build Directory
          command: |
            mkdir build
            cd build
            cmake -S ..
            make
            ctest

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build-and-test